#!/usr/bin/env python3
"""Installed-path e2e: exercise the REAL distribution flow into a scratch
DSH_HOME —

    dsh plugin --profile dsh-cctui add <this checkout>
    dsh --profile dsh-cctui

with the bundle's own cordis.patch.yml supplying the cctui row (the dev
patch only inserts the mock LLM and overrides the row's config), then drive
one streamed turn.
"""
import fcntl
import json
import os
import pty
import re
import select
import shutil
import signal
import struct
import subprocess
import sys
import termios
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HOME = ROOT / ".dsh-install-home"
PATCH = HOME / "install.cordis.yml"
DSH = ROOT / "node_modules" / "@deepseek-ai" / "dsh" / "lib" / "bin.js"
PROMPT_GLYPH = "❯"


def sh(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    print("  $", " ".join(str(c) for c in cmd))
    return subprocess.run(cmd, **kw)


def install() -> None:
    shutil.rmtree(HOME, ignore_errors=True)
    HOME.mkdir(parents=True)
    env = dict(os.environ)
    env["DSH_HOME"] = str(HOME)
    r = sh(
        ["node", str(DSH), "plugin", "--profile", "dsh-cctui", "add", str(ROOT)],
        env=env,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        timeout=900,
    )
    if r.returncode != 0:
        print(r.stdout[-3000:])
        print(r.stderr[-3000:])
        raise SystemExit("dsh plugin add failed")
    manifest = json.loads((HOME / "profiles" / "dsh-cctui" / "package.json").read_text())
    bundles = manifest.get("dsh", {}).get("profile", {}).get("bundles", [])
    print("  profile bundles:", bundles)
    assert "dsh-cctui" in bundles, "bundle not registered in the profile manifest"
    PATCH.write_text(
        f"""# generated by scripts/e2e/run_install.py
- id: hmr
  disabled: true
- id: cctui
  config:
    provider: mock
    model: mock-1
    cwd: '{ROOT}'
- insert:
    - id: mock-llm
      name: '{ROOT}/test/e2e/mock-llm.mjs'
"""
    )


def drive() -> list[str]:
    failures: list[str] = []
    env = dict(os.environ)
    env["DSH_HOME"] = str(HOME)
    env["NODE_ENV"] = "production"
    env["DSH_CCTUI_INLINE"] = "1"
    cmd = ["node", str(DSH), "--profile", "dsh-cctui", "--patch", str(PATCH)]
    master, slave = pty.openpty()
    fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 120, 0, 0))
    os.set_inheritable(slave, True)
    proc = subprocess.Popen(
        cmd, stdin=slave, stdout=slave, stderr=slave, env=env, cwd=str(ROOT), close_fds=True, preexec_fn=os.setsid
    )
    os.close(slave)
    transcript = bytearray()

    def flat() -> str:
        t = bytes(transcript).decode("utf-8", "replace")
        t = re.sub(r"\x1b\[[0-9]*C", " ", t)
        t = re.sub(r"\x1b\[[0-9;?<>=]*[A-Za-z]", "", t)
        t = re.sub(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)", "", t)
        return re.sub(r"\s+", " ", t)

    def pump(needles: list[str], timeout: float) -> str | None:
        deadline = time.time() + timeout
        while time.time() < deadline:
            r, _, _ = select.select([master], [], [], 0.25)
            if master in r:
                try:
                    chunk = os.read(master, 65536)
                except OSError:
                    break
                if not chunk:
                    break
                transcript.extend(chunk)
                replies = []
                if b"\x1b[c" in chunk:
                    replies.append(b"\x1b[?62;22c")
                for _ in re.findall(rb"\x1b\[6n", chunk):
                    replies.append(b"\x1b[40;1R")
                if b"\x1b]11;?" in chunk:
                    replies.append(b"\x1b]11;rgb:1e1e/1e1e/1e1e\x1b\\")
                if b"\x1b[?2026$p" in chunk:
                    replies.append(b"\x1b[?2026;2$y")
                if replies:
                    os.write(master, b"".join(replies))
            f = flat()
            for needle in needles:
                if needle in f:
                    return needle
            if proc.poll() is not None:
                break
        f = flat()
        for needle in needles:
            if needle in f:
                return needle
        return None

    try:
        if not pump([PROMPT_GLYPH], 90):
            failures.append("install boot: composer never rendered")
        else:
            pump([], 1.0)
            os.write(master, b"hello installed world")
            pump([], 0.5)
            os.write(master, b"\r")
            if not pump(["MOCK-REPLY: hello installed world"], 60):
                failures.append("install boot: streamed reply never rendered")
            pump([], 1.0)
            os.write(master, b"/quit")
            pump([], 0.5)
            os.write(master, b"\x1b")
            pump([], 0.3)
            os.write(master, b"\r")
            pump([], 2.0)
        try:
            proc.wait(timeout=20)
        except subprocess.TimeoutExpired:
            failures.append("install boot: did not exit after /quit")
    finally:
        if proc.poll() is None:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except OSError:
                pass
        try:
            os.close(master)
        except OSError:
            pass
        (HOME / "e2e-install.transcript").write_bytes(bytes(transcript))
    return failures


def run() -> int:
    print("== install ==")
    install()
    print("== drive ==")
    failures = drive()
    if failures:
        print(f"\ninstall e2e FAILED: {failures}")
        t = (HOME / "e2e-install.transcript").read_bytes().decode("utf-8", "replace")
        print("--- tail ---")
        print(t[-2000:])
        return 1
    print("\ninstall e2e PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(run())
