#!/usr/bin/env python3
"""Stage 4 e2e: boot the real dsh (from this repo's node_modules) with the
dsh-base bundle + the built cc-tui plugin + a scripted mock LLM, inside a
real PTY. Type a prompt, watch the streamed reply render, quit, and assert
on the captured transcript.

Everything (CLI, loader, harness packages, plugin externals) resolves from
this repo's node_modules, so there is exactly one copy of every
@deepseek-ai package in the process.
"""
import fcntl
import json
import os
import pty
import re
import select
import signal
import struct
import subprocess
import sys
import termios
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HOME = ROOT / ".dsh-dev-home"
PROFILE = HOME / "profiles" / "cc"
PATCH = HOME / "dev.cordis.yml"
LOG = HOME / "e2e-core.transcript"

PROMPT_GLYPH = "❯"  # ❯


def bootstrap() -> None:
    PROFILE.mkdir(parents=True, exist_ok=True)
    (PROFILE / "package.json").write_text(
        json.dumps(
            {
                "name": "dsh-profile-cc",
                "private": True,
                "dependencies": {},
                "dsh": {"profile": {"bundles": ["@deepseek-ai/dsh-base"]}},
            },
            indent=2,
        )
    )
    PATCH.write_text(
        f"""# generated by scripts/e2e/run_core.py
- id: hmr
  disabled: true
- insert:
    - id: mock-llm
      name: '{ROOT}/test/e2e/mock-llm.mjs'
    - id: cc-tui
      name: '{ROOT}/dist/plugin.js'
      config:
        provider: mock
        model: mock-1
        cwd: '{ROOT}'
"""
    )


def run() -> int:
    bootstrap()
    env = dict(os.environ)
    env["DSH_HOME"] = str(HOME)
    env["NODE_ENV"] = "production"
    env["CLAWCODEX_TUI_INLINE"] = "1"
    env.pop("CLAWCODEX_TUI_THEME", None)

    cmd = [
        "node",
        str(ROOT / "node_modules" / "@deepseek-ai" / "dsh" / "lib" / "bin.js"),
        "--profile",
        "cc",
        "--patch",
        str(PATCH),
    ]

    master, slave = pty.openpty()
    # A realistic window; 0x0 (the openpty default) renders one glyph per row.
    fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 120, 0, 0))
    os.set_inheritable(slave, True)
    proc = subprocess.Popen(
        cmd,
        stdin=slave,
        stdout=slave,
        stderr=slave,
        env=env,
        cwd=str(ROOT),
        close_fds=True,
        preexec_fn=os.setsid,
    )
    os.close(slave)

    transcript = bytearray()
    deadline = time.time() + 120
    answered = set()

    def flatten(raw: bytes) -> str:
        t = raw.decode("utf-8", "replace")
        t = re.sub(r"\x1b\[[0-9]*C", " ", t)
        t = re.sub(r"\x1b\[[0-9;?<>=]*[A-Za-z]", "", t)
        t = re.sub(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\\\)", "", t)
        t = re.sub(r"[\r\n]+", " ", t)
        return re.sub(r"\s+", " ", t)

    def answer_queries(chunk: bytes) -> None:
        """Minimal terminal-emulator responses so the ink querier can settle."""
        replies = []
        if b"\x1b[c" in chunk or b"\x1b[0c" in chunk:
            replies.append(b"\x1b[?62;22c")  # DA1: VT220-ish
        for _ in re.findall(rb"\x1b\[6n", chunk):
            replies.append(b"\x1b[40;1R")  # CPR: bottom-left
        if (b"\x1b]11;?" in chunk) and ("osc11" not in answered):
            answered.add("osc11")
            replies.append(b"\x1b]11;rgb:1e1e/1e1e/1e1e\x1b\\")
        if b"\x1b[?2026$p" in chunk:
            replies.append(b"\x1b[?2026;2$y")  # sync updates supported
        if replies:
            os.write(master, b"".join(replies))

    def read_until(needles: list[str], step_timeout: float) -> str | None:
        """Drain PTY output until a needle appears in the FLATTENED transcript."""
        step_deadline = time.time() + step_timeout
        while time.time() < min(step_deadline, deadline):
            r, _, _ = select.select([master], [], [], 0.25)
            if master in r:
                try:
                    chunk = os.read(master, 65536)
                except OSError:
                    break
                if not chunk:
                    break
                transcript.extend(chunk)
                answer_queries(chunk)
            flat_now = flatten(bytes(transcript))
            for needle in needles:
                if needle in flat_now:
                    return needle
            if proc.poll() is not None:
                try:
                    while True:
                        chunk = os.read(master, 65536)
                        if not chunk:
                            break
                        transcript.extend(chunk)
                except OSError:
                    pass
                break
        flat_now = flatten(bytes(transcript))
        for needle in needles:
            if needle in flat_now:
                return needle
        return None

    def drain(seconds: float) -> None:
        end = time.time() + seconds
        while time.time() < end:
            r, _, _ = select.select([master], [], [], 0.2)
            if master in r:
                try:
                    chunk = os.read(master, 65536)
                except OSError:
                    return
                if not chunk:
                    return
                transcript.extend(chunk)
                answer_queries(chunk)
            if proc.poll() is not None:
                return

    failures: list[str] = []
    try:
        # 1. The composer prompt appears (UI mounted).
        if not read_until([PROMPT_GLYPH], 60):
            failures.append("composer prompt glyph never rendered")
        else:
            drain(1.0)  # let session.create settle
            # 2. Type a prompt and submit.
            os.write(master, b"hello harness")
            drain(0.5)
            os.write(master, b"\r")
            # 3. The mock reply streams to completion.
            if not read_until(["MOCK-REPLY: hello harness", "harness agent failed"], 45):
                failures.append("full mock reply never rendered")
            elif "harness agent failed" in flatten(bytes(transcript)):
                failures.append("agent failed to start")
            drain(1.5)
            # 4. Approval flow: trigger a bash tool call, approve it, watch it run.
            os.write(master, b"please USE-BASH now")
            drain(0.5)
            os.write(master, b"\r")
            gate = read_until(["Yes", "harness agent failed"], 45)
            if gate is None:
                failures.append("approval prompt never appeared")
            elif gate == "Yes":
                drain(0.5)
                os.write(master, b"1")  # approve once
                if not read_until(["TOOL-STEP-DONE"], 45):
                    failures.append("bash tool turn never completed after approval")
                if "e2e-bash-ok" not in flatten(bytes(transcript)):
                    # the tool trail shows the command result line
                    read_until(["e2e-bash-ok"], 10)
            drain(1.5)
            # 5. Quit via /quit.
            os.write(master, b"/quit")
            drain(0.5)
            os.write(master, b"\r")
            drain(2.0)
        proc.wait(timeout=20)
    except subprocess.TimeoutExpired:
        failures.append("process did not exit after /quit")
    finally:
        if proc.poll() is None:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except OSError:
                pass
        try:
            os.close(master)
        except OSError:
            pass

    LOG.write_bytes(bytes(transcript))
    text = transcript.decode("utf-8", "replace")
    # Renderers emit inter-word padding as cursor-forward moves; normalize the
    # transcript to plain prose before phrase checks.
    flat = re.sub(r"\x1b\[[0-9]*C", " ", text)
    flat = re.sub(r"\x1b\[[0-9;?<>=]*[A-Za-z]", "", flat)
    flat = re.sub(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\\\)", "", flat)
    flat = re.sub(r"[\r\n]+", " ", flat)
    flat = re.sub(r"\s+", " ", flat)

    checks = [
        ("banner/composer rendered", PROMPT_GLYPH in text),
        ("mock reply streamed", "MOCK-REPLY: hello harness" in flat),
        ("no unhandled errors", "Unhandled" not in flat and "harness agent failed" not in flat),
        ("approval prompt shown", "Yes" in flat and "bash" in flat),
        ("approved tool ran to completion", "TOOL-STEP-DONE" in flat),
    ]
    for label, ok in checks:
        print(f"  {'PASS' if ok else 'FAIL'}  {label}")
        if not ok:
            failures.append(label)

    if failures:
        print(f"\ne2e FAILED: {failures}")
        print(f"transcript: {LOG} ({len(transcript)} bytes)")
        tail = text[-3000:]
        print("--- transcript tail ---")
        print(tail)
        return 1

    print(f"\ne2e PASSED (transcript: {LOG}, {len(transcript)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(run())
